<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
use Cmfcmf\OpenWeatherMap;
use Cmfcmf\OpenWeatherMap\Exception as OWMException;

function sapient_brancott_preprocess_views_view_fields(&$variables) {
  global $base_url;

  $view_id = $variables['view']->storage->id();
  
  switch ($view_id) {
    case 'our_wines':
	
      if ($variables['view']->current_display == 'block_1') {
		
		$details = getRangeDetailsFiltered();
		$detail_array = array();
		foreach($details as $key => $detail){
			$detail_array[$key]['title'] = $detail->title;
			$detail_array[$key]['desc'] = $detail->description;
			$ids = \Drupal::entityQuery('node')
		  ->condition('title', $detail->title)
          ->condition('status', 1)
          ->execute();
		  $array_nid = array_values($ids);
		 $nid = $array_nid[0];
		 
		  
		  $node_load = \Drupal\node\Entity\Node::load($nid);
		  $bkg_color =  $node_load->field_ranges_background_color->value;
		  $range_image_target = $node_load->field_ranges_image->target_id;
		  $range_image_file = \Drupal\file\Entity\File::load($range_image_target);
		  if($range_image_file){
          $range_image_url = \Drupal\image\Entity\ImageStyle::load('medium')->buildUrl($range_image_file->getFileUri());
		  }
		  $detail_array[$key]['bkg_colr'] = $bkg_color;
		  $detail_array[$key]['range_image'] = $range_image_url;
		 
        		  
		}
		$variables['range_details'] = $detail_array;
		//print_r($detail_array);die;
      }
    case 'homepage_components':
      if ($variables['view']->current_display == 'common_hero_component') {

        if ($variables['row']->_entity->field_season_description) {
          $values = $variables['row']->_entity->field_season_description->getValue();
          $city = $variables['row']->_entity->field_city->value;

          $month = date('n');
          if (!empty($values[$month - 1])) {
            $variables['season_desc'] = $values[$month - 1]['value'];
          }
          else {
            $variables['season_desc'] = '';
          }
          $owm = new OpenWeatherMap('bd4028edc390aa0629042fefed9976ca');
          $weather = $owm->getWeather($city, 'metric');

          $icon_id = $weather->weather->icon;
          $basepath = base_path() . $variables['directory'];

          $variables['temp_icon'] = $base_url . $basepath . '/css/images\season_icons/' . $icon_id . '.svg';
          $variables['current_temp'] = round(html_entity_decode($weather->temperature->now));
          $variables['temp_unit'] = html_entity_decode($weather->temperature->getUnit());
		  //print_r($variables['current_temp']);echo"test";print_r($variables['temp_unit']);exit;
          $variables['current_date'] = date('d M Y / g:ia');
        }
      }
    case 'wines_hero_component':
      if ($variables['view']->current_display == 'wines_hero_component') {
        if ($variables['row']->_entity->field_wine_id) {
          $wine_id = $variables['row']->_entity->field_wine_id->value;
          $details = braoncott_rest_api_get_results($wine_id);
          $variables['wine_title'] = strtoupper($details->title);
          $variables['wine_range'] = strtoupper($details->range);
          $variables['wine_description'] = $details->description;
        }
      }
      if ($variables['view']->current_display == 'related_wines') {
        if ($variables['row']->_entity->field_wine_id) {
          $wine_id = $variables['row']->_entity->field_wine_id->value;
          $details = braoncott_rest_api_get_results($wine_id);
          $variables['wine_title'] = $details->title;
          $variables['wine_range'] = $details->range;
		  //$variables['wine_range_bkg_color'] = $details->range;
		  $ids = \Drupal::entityQuery('node')
		  ->condition('title', $details->range)
          ->condition('status', 1)
          //->condition('field_wine_id', $value->id)
          ->execute(); 
		  
		  $array_nid = array_values($ids);
		  $nid = $array_nid[0];
		  if($nid){
		  $bkg_color = \Drupal\node\Entity\Node::load($nid);
		  $bkg_color =  $bkg_color->field_ranges_background_color->value;
		  $variables['range_bkg_color'] = $bkg_color;
		  }
          //print_r($bkg_color);die('test2');
        }
      }
      if ($variables['view']->current_display == 'awards_and_accolades') {
        if ($variables['row']->_entity->field_wine_id) {
          $wine_id = $variables['row']->_entity->field_wine_id->value;
          $details = braoncott_rest_api_get_results($wine_id);
          $variables['wine_award'] = $details->wineAwards;
        }
      }
      if ($variables['view']->current_display == 'tasting_notes_component') {
        if ($variables['row']->_entity->field_wine_id) {
          $wine_id = $variables['row']->_entity->field_wine_id->value;
          $details = braoncott_rest_api_get_results($wine_id);
          $variables['tasting_notes_aroma'] = $details->aroma;
          $variables['tasting_notes_taste'] = $details->taste;
          $variables['tasting_notes_complement'] = $details->complement;
          $variables['wine_title'] = $details->title;
          $variables['nutritional_info_alcohol'] = $details->wineNutritional[0]->alcohol;
          $variables['nutritional_info_calories'] = $details->wineNutritional[0]->calories;
          $variables['nutritional_info_fat'] = $details->wineNutritional[0]->fat;
          $variables['nutritional_info_saturates'] = $details->wineNutritional[0]->saturates;
          $variables['nutritional_info_carbohydrates'] = $details->wineNutritional[0]->carbohydrates;
          $variables['nutritional_info_sugars'] = $details->wineNutritional[0]->sugars;
          $variables['nutritional_info_proteins'] = $details->wineNutritional[0]->proteins;
        }
      }
      break;
  }
}
