<?php
use Drupal\pr_ctbuy_connector\Controller\RemotekeyAutocompleteController;

function getInstancePairs() {
    $instance_pairs = array();
    $instances = \Drupal::config('pr_ctbuy_connector.settings')->get('pr_ctbuy_connector_instances');
    $instances_array = explode(',', $instances);
    foreach ($instances_array as $instance_details) {
      $instance_details = trim($instance_details);
      $instance_array = explode('|', $instance_details);
      if (trim($instance_array[1])) {
        $instance_pairs[$instance_array[0]] = trim($instance_array[1]);
      }
    }
    return $instance_pairs;
  }
  
  function pr_ctbuy_connector_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if ($form_id == 'node_wines_edit_form' or $form_id == 'node_wines_form' or $form_id == 'node_where_to_buy_edit_form' or $form_id == 'node_where_to_buy_form') {
    $pairs = getInstancePairs();
	if(array_key_exists($langcode,$pairs)){
	$instances_value = 0;
	}
	else{
	//unset($form['field_cta_options']['widget']['#options']['buy_now']);
	//$form['field_click_to_buy_hero_cta']['#access'] = false;
	}

  }
  if ($form_id == 'node_where_to_buy_edit_form' or $form_id == 'node_where_to_buy_form') {
    $pairs = getInstancePairs();
	if(array_key_exists($langcode,$pairs)){
	$instances_value = 0;
	}
	else{
	//unset($form['field_where_to_buy_cta_link']['widget']['#options']['buy_now']);
	//$form['field_click_to_buy_hero_cta']['#access'] = false;
	}

  }
}
